---
- name: 'Instalando o Mysql Server'
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - mysql-server
    - python3-mysqldb

- name: 'Cria o banco no MySQL'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
  become: yes

- name: 'Cria usuario no MySQL'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: '{{ item }}'
  with_items:
    - "{{ wp_host_ip}}"
  become: yes

- name: 'Configurando MySQL para aceitar conexões remotas'
  copy:
    src: 'files/mysqld8.cnf'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
  become: yes
  notify:
   - restart mysql